INSERT INTO categorie
 		(nom)
VALUES 
		('Art musique et cinéma'),
		('Auto-edition'),
		('Bandes dessinées'),
		('Cuisine'),
		('Développement personnel'),
		('Dictionnaires et langues'),
		('Droit et économie'),
		('Essaus et documents'),
		('Guides pratiques'),
		('Histoire'),
		('Humour'),
		('Informatique et internet'),
		('Jeunesse'),
		('Littérature'),
		('Littérature sentimentale'),
		('Policier, suspense, thrillers'),
		('Religion et spiritualité'),
		('Sciences sociales'),
		('Sciences techniques et médecine'),
		('Scolaire'),
		('SF, Fantasy'),
		('Sport loisirs et vie pratique'),
		('Théâtre'),
		('Tourisme et voyages');
